import type {
  YearCycle, Department, User, AuditorProfile,
  AuditPlan, CPAR, ManagementReview, KPI, KPIReport, MOC, Document,
} from "./types";

export const DEPARTMENTS: Department[] = [
  { id: "dept-mkt", code: "MKT", name: "Marketing" },
  { id: "dept-log", code: "LOG", name: "Logistics" },
  { id: "dept-dcc", code: "DCC", name: "Document Control" },
  { id: "dept-hr",  code: "HR",  name: "Human Resources" },
  { id: "dept-she", code: "SHE", name: "Safety Health & Environment" },
  { id: "dept-qc",  code: "QC",  name: "Quality Control" },
  { id: "dept-mfg", code: "MFG", name: "Manufacturing" },
  { id: "dept-it",  code: "IT",  name: "Information Technology" },
];

export const YEAR_CYCLES: YearCycle[] = [
  { id: "yc-2025", year: 2025, isActive: false, isClosed: true,  annualReportUrl: "https://example.com/report-2025.pdf", reportSubmittedAt: "2026-01-10T09:00:00.000Z", reportSubmittedBy: "Admin QMR" },
  { id: "yc-2026", year: 2026, isActive: true,  isClosed: false, annualReportUrl: null, reportSubmittedAt: null, reportSubmittedBy: null },
];

export const USERS: User[] = [
  { id: "usr-001", name: "Admin QMR",      email: "qmr@cmg.co.th",      role: "QMR",       departmentId: "dept-dcc", department: { id: "dept-dcc", code: "DCC", name: "Document Control" } },
  { id: "usr-002", name: "Somchai Jaidee", email: "somchai@cmg.co.th",  role: "AUDITOR",   departmentId: "dept-qc",  department: { id: "dept-qc",  code: "QC",  name: "Quality Control" } },
  { id: "usr-003", name: "Nattaya Ploy",   email: "nattaya@cmg.co.th",  role: "AUDITOR",   departmentId: "dept-she", department: { id: "dept-she", code: "SHE", name: "Safety Health & Environment" } },
  { id: "usr-004", name: "Kritsana Boom",  email: "kritsana@cmg.co.th", role: "AUDITEE",   departmentId: "dept-mkt", department: { id: "dept-mkt", code: "MKT", name: "Marketing" } },
  { id: "usr-005", name: "Panida Wan",     email: "panida@cmg.co.th",   role: "AUDITEE",   departmentId: "dept-log", department: { id: "dept-log", code: "LOG", name: "Logistics" } },
  { id: "usr-006", name: "Wichit Dee",     email: "wichit@cmg.co.th",   role: "DEPT_HEAD", departmentId: "dept-hr",  department: { id: "dept-hr",  code: "HR",  name: "Human Resources" } },
  { id: "usr-007", name: "Maneerat Sai",   email: "maneerat@cmg.co.th", role: "AUDITOR",   departmentId: "dept-it",  department: { id: "dept-it",  code: "IT",  name: "Information Technology" } },
  { id: "usr-008", name: "Thanit Prao",    email: "thanit@cmg.co.th",   role: "AUDITEE",   departmentId: "dept-mfg", department: { id: "dept-mfg", code: "MFG", name: "Manufacturing" } },
  { id: "usr-009", name: "Suda Kaew",      email: "suda@cmg.co.th",     role: "AUDITEE",   departmentId: "dept-it",  department: { id: "dept-it",  code: "IT",  name: "Information Technology" } },
];

export const AUDITOR_PROFILES: AuditorProfile[] = [
  {
    id: "aud-001", userId: "usr-002",
    user: USERS[1],
    isActiveAuditor: true,
    iso9001ExamPassed: true, iso45001ExamPassed: true,
    iso9001CertUrl: "https://example.com/cert9001-somchai.pdf",
    iso45001CertUrl: "https://example.com/cert45001-somchai.pdf",
  },
  {
    id: "aud-002", userId: "usr-003",
    user: USERS[2],
    isActiveAuditor: true,
    iso9001ExamPassed: true, iso45001ExamPassed: true,
    iso9001CertUrl: "https://example.com/cert9001-nattaya.pdf",
    iso45001CertUrl: "https://example.com/cert45001-nattaya.pdf",
  },
  {
    id: "aud-003", userId: "usr-007",
    user: USERS[6],
    isActiveAuditor: false,
    iso9001ExamPassed: true, iso45001ExamPassed: false,
    iso9001CertUrl: "https://example.com/cert9001-maneerat.pdf",
    iso45001CertUrl: null,
  },
];

export const KPIS: KPI[] = [
  { id: "kpi-001", yearCycleId: "yc-2026", departmentId: "dept-mkt", name: "Customer Satisfaction Score", target: 90,  unit: "%" },
  { id: "kpi-002", yearCycleId: "yc-2026", departmentId: "dept-mkt", name: "On-time Delivery Rate",       target: 95,  unit: "%" },
  { id: "kpi-003", yearCycleId: "yc-2026", departmentId: "dept-qc",  name: "Defect Rate",                 target: 2,   unit: "%" },
  { id: "kpi-004", yearCycleId: "yc-2026", departmentId: "dept-qc",  name: "First Pass Yield",            target: 98,  unit: "%" },
  { id: "kpi-005", yearCycleId: "yc-2026", departmentId: "dept-she", name: "Safety Incident Rate",        target: 0,   unit: "incidents" },
  { id: "kpi-006", yearCycleId: "yc-2026", departmentId: "dept-she", name: "Near Miss Reports",           target: 12,  unit: "reports/yr" },
  { id: "kpi-007", yearCycleId: "yc-2026", departmentId: "dept-hr",  name: "Training Hours per Employee", target: 40,  unit: "hours" },
  { id: "kpi-008", yearCycleId: "yc-2026", departmentId: "dept-log", name: "Inventory Accuracy",          target: 99,  unit: "%" },
  { id: "kpi-009", yearCycleId: "yc-2026", departmentId: "dept-mfg", name: "OEE (Overall Equipment Effectiveness)", target: 85, unit: "%" },
  { id: "kpi-010", yearCycleId: "yc-2026", departmentId: "dept-it",  name: "System Uptime",               target: 99.9, unit: "%" },
  // 2025
  { id: "kpi-011", yearCycleId: "yc-2025", departmentId: "dept-mkt", name: "Customer Satisfaction Score", target: 88, unit: "%" },
  { id: "kpi-012", yearCycleId: "yc-2025", departmentId: "dept-qc",  name: "Defect Rate",                 target: 3,  unit: "%" },
];

export const KPI_REPORTS: KPIReport[] = [
  // kpi-001 MKT Customer Satisfaction
  { id: "kpr-001", kpiId: "kpi-001", departmentId: "dept-mkt", yearId: "yc-2026", reportMonth: 1, value: 88, status: "LATE",    submittedAt: "2026-02-12T08:00:00.000Z" },
  { id: "kpr-002", kpiId: "kpi-001", departmentId: "dept-mkt", yearId: "yc-2026", reportMonth: 2, value: 91, status: "ON_TIME", submittedAt: "2026-03-04T09:00:00.000Z" },
  { id: "kpr-003", kpiId: "kpi-001", departmentId: "dept-mkt", yearId: "yc-2026", reportMonth: 3, value: 93, status: "ON_TIME", submittedAt: "2026-04-03T09:00:00.000Z" },
  // kpi-002 MKT On-time Delivery
  { id: "kpr-004", kpiId: "kpi-002", departmentId: "dept-mkt", yearId: "yc-2026", reportMonth: 1, value: 94, status: "ON_TIME", submittedAt: "2026-02-04T08:00:00.000Z" },
  { id: "kpr-005", kpiId: "kpi-002", departmentId: "dept-mkt", yearId: "yc-2026", reportMonth: 2, value: 96, status: "ON_TIME", submittedAt: "2026-03-05T09:00:00.000Z" },
  { id: "kpr-006", kpiId: "kpi-002", departmentId: "dept-mkt", yearId: "yc-2026", reportMonth: 3, value: 92, status: "ON_TIME", submittedAt: "2026-04-04T09:00:00.000Z" },
  // kpi-003 QC Defect Rate
  { id: "kpr-007", kpiId: "kpi-003", departmentId: "dept-qc",  yearId: "yc-2026", reportMonth: 1, value: 1.8, status: "ON_TIME", submittedAt: "2026-02-04T08:00:00.000Z" },
  { id: "kpr-008", kpiId: "kpi-003", departmentId: "dept-qc",  yearId: "yc-2026", reportMonth: 2, value: 2.1, status: "LATE",    submittedAt: "2026-03-08T11:00:00.000Z" },
  { id: "kpr-009", kpiId: "kpi-003", departmentId: "dept-qc",  yearId: "yc-2026", reportMonth: 3, value: 1.5, status: "ON_TIME", submittedAt: "2026-04-04T08:00:00.000Z" },
  // kpi-004 QC First Pass Yield
  { id: "kpr-010", kpiId: "kpi-004", departmentId: "dept-qc",  yearId: "yc-2026", reportMonth: 1, value: 97.5, status: "ON_TIME", submittedAt: "2026-02-04T08:00:00.000Z" },
  { id: "kpr-011", kpiId: "kpi-004", departmentId: "dept-qc",  yearId: "yc-2026", reportMonth: 2, value: 98.2, status: "ON_TIME", submittedAt: "2026-03-05T09:00:00.000Z" },
  { id: "kpr-012", kpiId: "kpi-004", departmentId: "dept-qc",  yearId: "yc-2026", reportMonth: 3, value: 98.8, status: "ON_TIME", submittedAt: "2026-04-04T09:00:00.000Z" },
  // kpi-005 SHE Safety Incidents
  { id: "kpr-013", kpiId: "kpi-005", departmentId: "dept-she", yearId: "yc-2026", reportMonth: 1, value: 0, status: "ON_TIME", submittedAt: "2026-02-03T08:00:00.000Z" },
  { id: "kpr-014", kpiId: "kpi-005", departmentId: "dept-she", yearId: "yc-2026", reportMonth: 2, value: 1, status: "ON_TIME", submittedAt: "2026-03-05T09:00:00.000Z" },
  { id: "kpr-015", kpiId: "kpi-005", departmentId: "dept-she", yearId: "yc-2026", reportMonth: 3, value: 0, status: "ON_TIME", submittedAt: "2026-04-02T08:00:00.000Z" },
  // kpi-007 HR Training Hours
  { id: "kpr-016", kpiId: "kpi-007", departmentId: "dept-hr",  yearId: "yc-2026", reportMonth: 1, value: 38, status: "LATE",    submittedAt: "2026-02-10T10:00:00.000Z" },
  { id: "kpr-017", kpiId: "kpi-007", departmentId: "dept-hr",  yearId: "yc-2026", reportMonth: 2, value: 42, status: "ON_TIME", submittedAt: "2026-03-04T09:00:00.000Z" },
  // kpi-008 LOG Inventory Accuracy
  { id: "kpr-018", kpiId: "kpi-008", departmentId: "dept-log", yearId: "yc-2026", reportMonth: 1, value: 98.5, status: "ON_TIME", submittedAt: "2026-02-04T08:00:00.000Z" },
  { id: "kpr-019", kpiId: "kpi-008", departmentId: "dept-log", yearId: "yc-2026", reportMonth: 2, value: 99.1, status: "ON_TIME", submittedAt: "2026-03-05T09:00:00.000Z" },
  { id: "kpr-020", kpiId: "kpi-008", departmentId: "dept-log", yearId: "yc-2026", reportMonth: 3, value: 99.3, status: "ON_TIME", submittedAt: "2026-04-04T09:00:00.000Z" },
];

export const AUDIT_PLANS: AuditPlan[] = [
  {
    id: "ap-001", yearCycleId: "yc-2026", auditType: "INTERNAL", roundNumber: 1,
    scheduledDate: "2026-02-15T00:00:00.000Z", status: "COMPLETED",
    departmentId: "dept-mkt", auditorId: "usr-002", auditeeId: "usr-004",
    auditee: { id: "usr-004", name: "Kritsana Boom", department: { id: "dept-mkt", code: "MKT", name: "Marketing" } },
    auditor: { id: "usr-002", name: "Somchai Jaidee" },
    cpars: [{ id: "cpar-001" }],
  },
  {
    id: "ap-002", yearCycleId: "yc-2026", auditType: "INTERNAL", roundNumber: 1,
    scheduledDate: "2026-03-10T00:00:00.000Z", status: "COMPLETED",
    departmentId: "dept-log", auditorId: "usr-003", auditeeId: "usr-005",
    auditee: { id: "usr-005", name: "Panida Wan", department: { id: "dept-log", code: "LOG", name: "Logistics" } },
    auditor: { id: "usr-003", name: "Nattaya Ploy" },
    cpars: [],
  },
  {
    id: "ap-003", yearCycleId: "yc-2026", auditType: "INTERNAL", roundNumber: 1,
    scheduledDate: "2026-04-20T00:00:00.000Z", status: "IN_PROGRESS",
    departmentId: "dept-hr", auditorId: "usr-002", auditeeId: "usr-006",
    auditee: { id: "usr-006", name: "Wichit Dee", department: { id: "dept-hr", code: "HR", name: "Human Resources" } },
    auditor: { id: "usr-002", name: "Somchai Jaidee" },
    cpars: [{ id: "cpar-002" }],
  },
  {
    id: "ap-004", yearCycleId: "yc-2026", auditType: "EXTERNAL", roundNumber: 1,
    scheduledDate: "2026-06-15T00:00:00.000Z", status: "PLANNED",
    departmentId: "dept-qc", auditorId: "usr-003", auditeeId: "usr-002",
    auditee: { id: "usr-002", name: "Somchai Jaidee", department: { id: "dept-qc", code: "QC", name: "Quality Control" } },
    auditor: { id: "usr-003", name: "Nattaya Ploy" },
    cpars: [],
  },
  {
    id: "ap-005", yearCycleId: "yc-2026", auditType: "INTERNAL", roundNumber: 2,
    scheduledDate: "2026-08-12T00:00:00.000Z", status: "PLANNED",
    departmentId: "dept-she", auditorId: "usr-002", auditeeId: "usr-003",
    auditee: { id: "usr-003", name: "Nattaya Ploy", department: { id: "dept-she", code: "SHE", name: "Safety Health & Environment" } },
    auditor: { id: "usr-002", name: "Somchai Jaidee" },
    cpars: [],
  },
  {
    id: "ap-006", yearCycleId: "yc-2026", auditType: "INTERNAL", roundNumber: 1,
    scheduledDate: "2026-05-08T00:00:00.000Z", status: "PLANNED",
    departmentId: "dept-it", auditorId: "usr-003", auditeeId: "usr-009",
    auditee: { id: "usr-009", name: "Suda Kaew", department: { id: "dept-it", code: "IT", name: "Information Technology" } },
    auditor: { id: "usr-003", name: "Nattaya Ploy" },
    cpars: [],
  },
  {
    id: "ap-007", yearCycleId: "yc-2026", auditType: "INTERNAL", roundNumber: 1,
    scheduledDate: "2026-07-22T00:00:00.000Z", status: "PLANNED",
    departmentId: "dept-mfg", auditorId: "usr-002", auditeeId: "usr-008",
    auditee: { id: "usr-008", name: "Thanit Prao", department: { id: "dept-mfg", code: "MFG", name: "Manufacturing" } },
    auditor: { id: "usr-002", name: "Somchai Jaidee" },
    cpars: [],
  },
  // 2025 audits
  {
    id: "ap-008", yearCycleId: "yc-2025", auditType: "INTERNAL", roundNumber: 1,
    scheduledDate: "2025-03-15T00:00:00.000Z", status: "CLOSED",
    departmentId: "dept-dcc", auditorId: "usr-002", auditeeId: "usr-001",
    auditee: { id: "usr-001", name: "Admin QMR", department: { id: "dept-dcc", code: "DCC", name: "Document Control" } },
    auditor: { id: "usr-002", name: "Somchai Jaidee" },
    cpars: [{ id: "cpar-003" }],
  },
];

export const CPARS: CPAR[] = [
  {
    id: "cpar-001", cparNo: "CPAR-2026-001", auditId: "ap-001", yearCycleId: "yc-2026",
    title: "Customer Complaint Handling Procedure",
    description: "Procedure for handling customer complaints is not consistently followed by MKT staff",
    status: "PENDING_VERIFICATION",
    rootCause: "Staff not trained on updated procedure QP-MKT-003 Rev.2",
    correctiveAction: "Conducted training session for all MKT staff on 2026-03-01. Training records updated in FM-HR-002.",
    verificationResult: null,
    issuedDate: "2026-02-18T00:00:00.000Z",
    dueDate: "2026-04-18T00:00:00.000Z",
    closedDate: null,
    departmentId: "dept-mkt",
    department: { id: "dept-mkt", code: "MKT", name: "Marketing" },
  },
  {
    id: "cpar-002", cparNo: "CPAR-2026-002", auditId: "ap-003", yearCycleId: "yc-2026",
    title: "Training Records Incomplete",
    description: "Several employees missing mandatory ISO 9001 awareness training records for 2025",
    status: "PLANNING",
    rootCause: "Training tracking spreadsheet not updated since Q4 2025 due to system migration",
    correctiveAction: null,
    verificationResult: null,
    issuedDate: "2026-04-22T00:00:00.000Z",
    dueDate: "2026-06-22T00:00:00.000Z",
    closedDate: null,
    departmentId: "dept-hr",
    department: { id: "dept-hr", code: "HR", name: "Human Resources" },
  },
  {
    id: "cpar-003", cparNo: "CPAR-2025-005", auditId: "ap-008", yearCycleId: "yc-2025",
    title: "Document Version Control Issue",
    description: "Obsolete documents found in active work area in Document Control department",
    status: "CLOSED",
    rootCause: "Document retrieval process not enforced during relocation",
    correctiveAction: "Removed all obsolete documents. Implemented document retrieval checklist POL-DCC-002.",
    verificationResult: "All obsolete documents removed and confirmed by QMR. Checklist implemented and verified on 2025-11-01.",
    issuedDate: "2025-09-10T00:00:00.000Z",
    dueDate: "2025-11-10T00:00:00.000Z",
    closedDate: "2025-11-05T00:00:00.000Z",
    departmentId: "dept-dcc",
    department: { id: "dept-dcc", code: "DCC", name: "Document Control" },
  },
  {
    id: "cpar-004", cparNo: "CPAR-2026-003", auditId: "ap-001", yearCycleId: "yc-2026",
    title: "Supplier Evaluation Not Conducted",
    description: "Annual supplier evaluation for key MKT suppliers was overdue by 3 months",
    status: "ISSUED",
    rootCause: null,
    correctiveAction: null,
    verificationResult: null,
    issuedDate: "2026-03-10T00:00:00.000Z",
    dueDate: "2026-05-10T00:00:00.000Z",
    closedDate: null,
    departmentId: "dept-mkt",
    department: { id: "dept-mkt", code: "MKT", name: "Marketing" },
  },
];

export const MANAGEMENT_REVIEWS: ManagementReview[] = [
  {
    id: "mr-001", yearCycleId: "yc-2026",
    title: "Q1 2026 Management Review Meeting",
    meetingDate: "2026-03-28T09:00:00.000Z",
    status: "COMPLETED",
    agendaUrl: "https://example.com/mr-q1-2026-agenda.pdf",
    minutesUrl: "https://example.com/mr-q1-2026-minutes.pdf",
    notes: "Reviewed Q1 KPI results, 2 CPAR open items discussed. Audit schedule confirmed. All Q1 objectives met. Next meeting: June 2026.",
  },
  {
    id: "mr-002", yearCycleId: "yc-2026",
    title: "Q2 2026 Management Review Meeting",
    meetingDate: "2026-06-30T09:00:00.000Z",
    status: "SCHEDULED",
    agendaUrl: null,
    minutesUrl: null,
    notes: null,
  },
  {
    id: "mr-003", yearCycleId: "yc-2026",
    title: "Mid-Year ISO Surveillance Preparation",
    meetingDate: "2026-05-15T09:00:00.000Z",
    status: "SCHEDULED",
    agendaUrl: null,
    minutesUrl: null,
    notes: "Pre-external audit preparation meeting with all department heads.",
  },
  {
    id: "mr-004", yearCycleId: "yc-2025",
    title: "Annual Management Review 2025",
    meetingDate: "2025-12-10T09:00:00.000Z",
    status: "COMPLETED",
    agendaUrl: "https://example.com/mr-annual-2025-agenda.pdf",
    minutesUrl: "https://example.com/mr-annual-2025-minutes.pdf",
    notes: "Year-end review. All KPIs reviewed. ISO recertification confirmed. Year closed.",
  },
];

export const MOCS: MOC[] = [
  {
    id: "moc-001", yearCycleId: "yc-2026",
    mocNo: "MOC-2026-001",
    title: "New ERP System Implementation",
    description: "Management of change for transitioning from legacy ERP to SAP S/4HANA across all departments. Affects all ISO-related processes and document workflows.",
    status: "ACTION_IN_PROGRESS",
    requestorId: "usr-001",
    requestor: USERS[0],
    createdAt: "2026-01-15T08:00:00.000Z",
    updatedAt: "2026-03-01T10:00:00.000Z",
  },
  {
    id: "moc-002", yearCycleId: "yc-2026",
    mocNo: "MOC-2026-002",
    title: "Warehouse Layout Restructuring",
    description: "Reconfiguring warehouse storage zones to improve forklift safety and comply with ISO 45001 aisle width requirements.",
    status: "PENDING_APPROVAL",
    requestorId: "usr-005",
    requestor: USERS[4],
    createdAt: "2026-02-20T08:00:00.000Z",
    updatedAt: "2026-02-20T08:00:00.000Z",
  },
  {
    id: "moc-003", yearCycleId: "yc-2026",
    mocNo: "MOC-2026-003",
    title: "ISO 45001 PPE Requirements Update",
    description: "Update personal protective equipment specifications based on ISO 45001:2018 clause 8.1.2 operational control requirements.",
    status: "MEETING_SETUP",
    requestorId: "usr-003",
    requestor: USERS[2],
    createdAt: "2026-04-05T08:00:00.000Z",
    updatedAt: "2026-04-05T08:00:00.000Z",
  },
  {
    id: "moc-004", yearCycleId: "yc-2026",
    mocNo: "MOC-2026-004",
    title: "Quality Lab Equipment Calibration Process",
    description: "New automated calibration tracking system to replace manual records, affecting QP-QC-004.",
    status: "CLOSED",
    requestorId: "usr-002",
    requestor: USERS[1],
    createdAt: "2026-01-20T08:00:00.000Z",
    updatedAt: "2026-03-15T10:00:00.000Z",
  },
];

export const DOCUMENTS: Document[] = [
  {
    id: "doc-001", docNo: "QP-QMS-001", category: "PROCEDURE", revision: "Rev.3", status: "ACTIVE",
    title: "Quality Management System Manual",
    description: "Defines the scope, structure, and application of the QMS across all departments",
    departmentId: "dept-dcc", department: { id: "dept-dcc", code: "DCC", name: "Document Control" },
    ownerId: "usr-001", owner: USERS[0],
    issuedDate: "2024-01-01T00:00:00.000Z", nextReviewDate: "2027-01-01T00:00:00.000Z",
    fileUrl: "https://example.com/qp-qms-001.pdf", relatedCparId: null, relatedMocId: null,
  },
  {
    id: "doc-002", docNo: "QP-MKT-003", category: "PROCEDURE", revision: "Rev.2", status: "ACTIVE",
    title: "Customer Complaint Handling Procedure",
    description: "Process for receiving, investigating, and resolving customer complaints",
    departmentId: "dept-mkt", department: { id: "dept-mkt", code: "MKT", name: "Marketing" },
    ownerId: "usr-004", owner: USERS[3],
    issuedDate: "2023-06-01T00:00:00.000Z", nextReviewDate: "2026-06-01T00:00:00.000Z",
    fileUrl: null, relatedCparId: "cpar-001", relatedMocId: null,
  },
  {
    id: "doc-003", docNo: "WI-SHE-005", category: "WORK_INSTRUCTION", revision: "Rev.1", status: "ACTIVE",
    title: "Hazardous Material Handling Work Instruction",
    description: "Step-by-step instructions for safely handling, storing, and disposing of hazardous materials",
    departmentId: "dept-she", department: { id: "dept-she", code: "SHE", name: "Safety Health & Environment" },
    ownerId: "usr-003", owner: USERS[2],
    issuedDate: "2025-03-01T00:00:00.000Z", nextReviewDate: "2028-03-01T00:00:00.000Z",
    fileUrl: "https://example.com/wi-she-005.pdf", relatedCparId: null, relatedMocId: null,
  },
  {
    id: "doc-004", docNo: "FM-HR-002", category: "FORM", revision: "Rev.4", status: "ACTIVE",
    title: "Employee Training Record Form",
    description: "Form for recording employee training completion, assessment scores, and certification outcomes",
    departmentId: "dept-hr", department: { id: "dept-hr", code: "HR", name: "Human Resources" },
    ownerId: "usr-006", owner: USERS[5],
    issuedDate: "2022-01-01T00:00:00.000Z", nextReviewDate: "2025-01-01T00:00:00.000Z",
    fileUrl: null, relatedCparId: "cpar-002", relatedMocId: null,
  },
  {
    id: "doc-005", docNo: "POL-QMS-001", category: "POLICY", revision: "Rev.2", status: "ACTIVE",
    title: "Quality Policy Statement",
    description: "Company Quality Policy signed by top management — commitment to customer satisfaction and continual improvement",
    departmentId: "dept-dcc", department: { id: "dept-dcc", code: "DCC", name: "Document Control" },
    ownerId: "usr-001", owner: USERS[0],
    issuedDate: "2024-01-01T00:00:00.000Z", nextReviewDate: "2027-01-01T00:00:00.000Z",
    fileUrl: "https://example.com/pol-qms-001.pdf", relatedCparId: null, relatedMocId: null,
  },
  {
    id: "doc-006", docNo: "POL-SHE-001", category: "POLICY", revision: "Rev.2", status: "UNDER_REVIEW",
    title: "Occupational Health & Safety Policy",
    description: "Company OH&S Policy per ISO 45001:2018 clause 5.2 — under annual review",
    departmentId: "dept-she", department: { id: "dept-she", code: "SHE", name: "Safety Health & Environment" },
    ownerId: "usr-003", owner: USERS[2],
    issuedDate: "2024-01-01T00:00:00.000Z", nextReviewDate: "2027-01-01T00:00:00.000Z",
    fileUrl: null, relatedCparId: null, relatedMocId: null,
  },
  {
    id: "doc-007", docNo: "EXT-ISO-9001", category: "EXTERNAL", revision: "2015", status: "ACTIVE",
    title: "ISO 9001:2015 International Standard",
    description: "International Standard for Quality Management Systems — reference document",
    departmentId: "dept-dcc", department: { id: "dept-dcc", code: "DCC", name: "Document Control" },
    ownerId: "usr-001", owner: USERS[0],
    issuedDate: "2015-09-15T00:00:00.000Z", nextReviewDate: "2030-01-01T00:00:00.000Z",
    fileUrl: "https://www.iso.org/standard/62085.html", relatedCparId: null, relatedMocId: null,
  },
  {
    id: "doc-008", docNo: "EXT-ISO-45001", category: "EXTERNAL", revision: "2018", status: "ACTIVE",
    title: "ISO 45001:2018 International Standard",
    description: "International Standard for Occupational Health and Safety Management Systems",
    departmentId: "dept-she", department: { id: "dept-she", code: "SHE", name: "Safety Health & Environment" },
    ownerId: "usr-003", owner: USERS[2],
    issuedDate: "2018-03-12T00:00:00.000Z", nextReviewDate: "2030-01-01T00:00:00.000Z",
    fileUrl: "https://www.iso.org/standard/63787.html", relatedCparId: null, relatedMocId: null,
  },
  {
    id: "doc-009", docNo: "QP-LOG-002", category: "PROCEDURE", revision: "Rev.1", status: "DRAFT",
    title: "Goods Receiving Procedure",
    description: "Procedure for receiving, inspecting, and recording incoming goods in the warehouse",
    departmentId: "dept-log", department: { id: "dept-log", code: "LOG", name: "Logistics" },
    ownerId: "usr-005", owner: USERS[4],
    issuedDate: "2026-03-01T00:00:00.000Z", nextReviewDate: "2029-03-01T00:00:00.000Z",
    fileUrl: null, relatedCparId: null, relatedMocId: "moc-001",
  },
  {
    id: "doc-010", docNo: "WI-QC-003", category: "WORK_INSTRUCTION", revision: "Rev.2", status: "ACTIVE",
    title: "Product Inspection Work Instruction",
    description: "Step-by-step final product inspection process including sampling plans and acceptance criteria",
    departmentId: "dept-qc", department: { id: "dept-qc", code: "QC", name: "Quality Control" },
    ownerId: "usr-002", owner: USERS[1],
    issuedDate: "2024-06-01T00:00:00.000Z", nextReviewDate: "2027-06-01T00:00:00.000Z",
    fileUrl: "https://example.com/wi-qc-003.pdf", relatedCparId: null, relatedMocId: null,
  },
  {
    id: "doc-011", docNo: "FM-SHE-001", category: "FORM", revision: "Rev.3", status: "ACTIVE",
    title: "Hazard Identification & Risk Assessment Form",
    description: "HIRA form for identifying workplace hazards, assessing risk levels, and planning controls",
    departmentId: "dept-she", department: { id: "dept-she", code: "SHE", name: "Safety Health & Environment" },
    ownerId: "usr-003", owner: USERS[2],
    issuedDate: "2023-01-01T00:00:00.000Z", nextReviewDate: "2026-01-01T00:00:00.000Z",
    fileUrl: null, relatedCparId: null, relatedMocId: null,
  },
  {
    id: "doc-012", docNo: "QP-QC-004", category: "PROCEDURE", revision: "Rev.1", status: "UNDER_REVIEW",
    title: "Equipment Calibration Procedure",
    description: "Calibration schedule and process for all quality lab equipment — under review for automation",
    departmentId: "dept-qc", department: { id: "dept-qc", code: "QC", name: "Quality Control" },
    ownerId: "usr-002", owner: USERS[1],
    issuedDate: "2022-09-01T00:00:00.000Z", nextReviewDate: "2025-09-01T00:00:00.000Z",
    fileUrl: null, relatedCparId: null, relatedMocId: "moc-004",
  },
];
